### ISSUE TITLE
Add open graph image

### ISSUE THREAD

**Issue by leo** [hakkens/phonebloks#11]
@davehakkens Can you please create one (like for precious plastic)? It's the one that also shows up on facebook and twitter, for example.

<img width="291" alt="screen shot 2016-04-23 at 18 35 52" src="https://cloud.githubusercontent.com/assets/6170607/14762726/4b74b666-0982-11e6-9392-25a3058efab7.png">

**Comment by davehakkens** [comment]
![phonebloks icon](https://cloud.githubusercontent.com/assets/13672737/14765630/afc80c6e-0a07-11e6-8960-a1c45cdaf6fd.png)

**Comment by leo** [comment]
@davehakkens Thanks!
