### ISSUE TITLE
Change the overall-look of "Journey"

### ISSUE THREAD

**Issue by leo** [hakkens/phonebloks#5]
@davehakkens suggested the following things:
- Would it be easy to change the direction of the timeline?
- The line after the last post shouln't end in the footer, rather in a dot that says "Today".

I'd say it's better to set the final direction now, because it takes a bit of effort. So which direction do you want, @davehakkens?

**Comment by davehakkens** [comment]
keep it like it is!

**Comment by leo** [comment]
Alright, sir! :blush:
